all: p2_1 p2_2 p2_3 p2_4

p2_1: p2_1.cpp
	g++ -g p2_1.cpp ../../DataStructures/LinkedList/singly_linked_list.cpp -o p2_1

p2_2: p2_2.cpp
	g++ -g p2_2.cpp ../../DataStructures/LinkedList/singly_linked_list.cpp -o p2_2

p2_3: p2_3.cpp
	g++ -g p2_3.cpp ../../DataStructures/LinkedList/singly_linked_list.cpp -o p2_3

p2_4: p2_4.cpp
	g++ -g p2_4.cpp ../../DataStructures/LinkedList/singly_linked_list.cpp -o p2_4
