all: p3_1 p3_2 p3_5 ../../DataStructures/Stacks_and_Queues/stack_linked_list.hpp

p3_1: p3_1.cpp
	g++ -g p3_1.cpp -o p3_1
p3_2: p3_2.cpp
	g++ -g p3_2.cpp -o p3_2
p3_5: p3_5.cpp
	g++ -g p3_5.cpp -o p3_5