all: p4_1 p4_2 p4_3

p4_1: p4_1.cpp ../../DataStructures/TreesAndGraphs/binary_tree.cpp
	g++ -g p4_1.cpp ../../DataStructures/TreesAndGraphs/binary_tree.cpp -o p4_1

p4_2: p4_2.cpp
	g++ -g p4_2.cpp -o p4_2

p4_3: p4_3.cpp
	g++ -g p4_3.cpp -o p4_3
